### ISSUE TITLE
core: provide multiple aggregates load in a bulk

### ISSUE THREAD

**Issue by mlesikov** [clouway/kcqrs#23]
it would be a huge improvement if we can load multiple aggregates in a single aggregate repository call 
```java
List<Invoice>invoices = aggregateRepository.load(ids,  Invoice.class)
```

**Comment by mgenov** [comment]
Sounds like a good idea. It is better to be returned ```Map<String, Invoice> ``` instead of List as the Id is going to be associated with it's aggregate.
