### ISSUE TITLE
kcqrs: transfer error message via PublishErrorException 

### ISSUE THREAD

**Issue by VasilMitovClouway** [clouway/kcqrs#32]
Right now in SyncEventPublisher when an error is thrown of any kind it is caught and a PublishErrorException is thrown so that the SimpleAggregateRepository may revert the last events. 
It would be valuable if the caught Exception's message to be transferred via the PublishErrorException as well. Or maybe a common Exception class may be created to be used to throw exceptions in the chain with the capabilities to carry a payload of sorts that will be later used by the http layer to translate this payload to a usable reason for the thrown exception.

**Comment by VasilMitovClouway** [comment]
@mgenov Do you think this functionality will help us, or the correct way would be to perform all validations before sending the message thus clearing all possibilities of errors in the chain of events.

**Comment by mgenov** [comment]
Yes, the client should know that some failure has occurred in the EventStore and events are not saved. Sounds reasonable to me.
